### ISSUE TITLE
when is the new release to support electron with node.js 6.3?

### ISSUE THREAD

**Issue by mksuper1** [kexplo/electron-edge#14]

**Comment by patroza** [comment]
I have a 1.3.1 Electron fork at https://github.com/sickboy/edge/tree/electron based on the latest tjanczuk/edge

Also because of VC++ 2015 you need to install the VC++ 2015 runtime components on systems.
The reason why I didn't include it with the build is because on systems older than Win10, other Windows Updates are required. They are installed by the [VC++ 2015 runtime installer](https://www.microsoft.com/en-us/download/details.aspx?id=52982) (I use this myself: https://github.com/sickboy/VCRedistInstaller)
